"""empty message

Revision ID: 19ce7a71d891
Revises: be64ef826d04
Create Date: 2018-09-29 21:26:03.857275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ce7a71d891'
down_revision = 'be64ef826d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('display_time', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'display_time')
    # ### end Alembic commands ###
