"""empty message

Revision ID: 3a5fcee69cde
Revises: be64ef826d04
Create Date: 2018-09-27 12:05:13.385082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5fcee69cde'
down_revision = 'be64ef826d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'category', ['name'], unique=True)
    # ### end Alembic commands ###
