"""empty message

Revision ID: a114143ea282
Revises: 93a3572fe986
Create Date: 2018-09-11 23:39:25.982900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a114143ea282'
down_revision = '93a3572fe986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('category_id', sa.String(length=16), nullable=False))
    op.add_column('article', sa.Column('seo_id', sa.String(length=16), nullable=True))
    op.drop_column('article', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('category', mysql.VARCHAR(length=16), nullable=False))
    op.drop_column('article', 'seo_id')
    op.drop_column('article', 'category_id')
    # ### end Alembic commands ###
