"""empty message

Revision ID: a87c647e28c3
Revises: 6082eaff392e
Create Date: 2018-09-11 22:46:04.161813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87c647e28c3'
down_revision = '6082eaff392e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('site_code', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'site', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_column('category', 'site_code')
    # ### end Alembic commands ###
